-- ============================================================================
-- CL3. RESEARCH HUB — iscm_research_list (Supabase DDL)
-- Official database model mapped from "2026 ISCM - RESEARCH - Research List.tsv"
-- Drives the table view inside the Research List page (CL3 Research Sub-Workspace).
-- Generated by scripts/gen-research-sql.mjs — edit src/data/researchList.js instead.
-- ============================================================================

-- Create the main research activity tracking table
CREATE TABLE iscm_research_list (
    id SERIAL PRIMARY KEY,
    code VARCHAR(50) NULL,
    research_unit VARCHAR(150) NOT NULL,
    task_name TEXT NOT NULL,
    status VARCHAR(100) DEFAULT 'Not start',
    start_year VARCHAR(10) NULL,
    end_year VARCHAR(10) NULL,
    task_type VARCHAR(100) NULL,
    ordered_by VARCHAR(100) NULL,
    coordinator_manager VARCHAR(150) NULL,
    members TEXT NULL,
    report_plan_link TEXT NULL,
    framework_transition VARCHAR(100) NULL,
    glocal_design VARCHAR(100) NULL,
    human_centric_orientation VARCHAR(100) NULL,
    tech_solutions VARCHAR(100) NULL,
    urban_system VARCHAR(100) NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Fields the Research List drawer edits (Classification tab, Members tab
    -- role tags, and the Documents tab's two upload lists).
    sdgs TEXT NULL,
    member_roles   JSONB NOT NULL DEFAULT '{}'::jsonb,  -- { "<member name>": "Head" | "Coordinator" | ... }
    minute_reports JSONB NOT NULL DEFAULT '[]'::jsonb,  -- [{ id, name, addedAt }]
    documents      JSONB NOT NULL DEFAULT '[]'::jsonb,  -- [{ id, name, addedAt }]
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable Row Level Security (RLS) for privacy settings control
ALTER TABLE iscm_research_list ENABLE ROW LEVEL SECURITY;

-- Director and Authorized Staff Global Access Policy
CREATE POLICY "Allow authenticated read access"
ON iscm_research_list FOR SELECT
TO authenticated
USING (true);

-- Writes (INSERT/UPDATE/DELETE) are restricted to a top admin or the head of
-- Scientific Research via can_manage_group(); see the policies named
-- "iscm_research_list write/update/delete (research head)" in the project.
-- The app surfaces a rejection to the user instead of pretending it saved.

-- ----------------------------------------------------------------------------
-- SEED — representative subset of the 2026 Research List TSV (all 10 units).
-- Import the full sheet later via CSV import against the same columns.
-- ----------------------------------------------------------------------------
INSERT INTO iscm_research_list
  (code, research_unit, task_name, status, start_year, end_year, task_type, ordered_by, coordinator_manager, members, report_plan_link, framework_transition, glocal_design, human_centric_orientation, tech_solutions, urban_system)
VALUES
  ('RU8', 'Data Driven and Urban Design', 'DDUD Main Folder', 'In progress', '2026', NULL, 'IRL', 'ISCM', 'Ms. Chi', 'TuAnh-Lead, Quang, Hùng', NULL, 'Không', NULL, NULL, 'Tech Solutions', NULL),
  ('RU8.1', 'Data Driven and Urban Design', 'Urban Heat', 'In progress', '2026', '2027', 'Research', 'Chi_Quang/ISCM', 'Ms. Chi', 'Quang, Hùng', 'Link', 'Không', NULL, NULL, 'Tech Solutions', NULL),
  ('RU8.1.1', 'Data Driven and Urban Design', 'Data-driven techniques', 'In progress', '2026', '2026', 'Research', 'Chi/ISCM', 'Mr. An', 'Chi, Hùng', 'Link', 'Không', NULL, NULL, 'Tech Solutions', NULL),
  ('RU8.1.2', 'Data Driven and Urban Design', 'Resilient design towards flood and heat', 'In progress', '2026', '2026', 'Paper', 'Hung/ISCM', 'Ms. Chi', 'Quang, Hùng', 'Link', 'Không', NULL, NULL, 'Tech Solutions', NULL),
  ('RU8.2', 'Data Driven and Urban Design', 'GIS training for staff', 'In progress', '2026', '2026', 'Training', 'ISCM', 'Ms. Chi', 'Quang, Hùng, An, Tài, Phúc, Khôi, Trâm', 'Link', 'Không', NULL, NULL, 'Tech Solutions', NULL),
  ('RU8.3', 'Data Driven and Urban Design', 'CTD Scholars 2: perceived safety in Hẻm system', 'In progress', '2026', '2026', 'Student research', 'Chi/ISCM', 'Ms. Chi', 'Hùng', 'Link', 'Không', NULL, NULL, 'Tech Solutions', NULL),
  ('RU9', 'Fund Raising', 'Fund Raising Main Folder', 'In progress', '2023', NULL, 'Fund Raising', NULL, 'Mr. Quang', 'TuAnh-Lead, Chi, Sandhya, Minh, Long, Hiền', NULL, 'Không', NULL, NULL, NULL, NULL),
  (NULL, 'Fund Raising', 'K-City Network', 'Funded', '2026', '3/2026', 'Project', 'Korean Government/ISCM', 'Mr. Quang', 'TuAnh-Lead, Sandhya, Chi, An, DSA: Thao, Duy', 'Moved to Smart Mobility Lab', 'Không', NULL, 'Human Centric Orientation', 'Tech Solutions', 'Urban System'),
  (NULL, 'Fund Raising', 'Global Gateway', 'Submitted/ Termination', '2026', '2026', 'New initiative', 'Sandhya/ISCM', 'Ms. Sandhya', 'Daniela, Quang', 'Project; Submitted', 'Framework Transition', 'Global Design', 'Human Centric Orientation', NULL, 'Urban System'),
  (NULL, 'Fund Raising', 'Mekong-ROK Cooperation', 'Submitted/ Termination', '2026', '2026', 'New initiative', 'Julia/ISCM', 'Mr. Minh', 'Chi, Trung Nexus', 'Project; Submitted', 'Framework Transition', NULL, 'Human Centric Orientation', NULL, 'Urban System'),
  (NULL, 'Fund Raising', 'CLARE', 'In progress', '2026', NULL, 'New initiative', 'Sandhya/ISCM', 'Mr. Long', 'Sandhya, Daniela, Quang, Vũ Bạch', NULL, 'Không', NULL, NULL, NULL, NULL),
  ('RU4', 'Governance and Planning', 'GPI Main Folder', 'On hold', '2022', '2024', 'PL', 'ISCM', 'Ms. Mai', 'TuAnh-Lead, Lan, Vũ, Phúc', NULL, 'Framework Transition', NULL, NULL, NULL, NULL),
  ('RU4.1', 'Governance and Planning', 'Quy hoạch Tỉnh Đồng Nai', 'Submitted/ Termination', '2025', '4/2026', 'Project', 'HIDS/STC ĐN', 'Mr. Tâm', 'TuAnh-Lead, Lan, Hiền, Mai, Chi, Vũ, Tài', 'Đang hoàn thiện báo cáo QHT', 'Framework Transition', NULL, NULL, NULL, NULL),
  (NULL, 'Governance and Planning', 'Hội thảo Luật Đô thị Đặc biệt', 'Done', '2026', '2026', 'Event', 'UEH', 'Ms. Lan', 'TuAnh-Lead, Mai, Hoài, Minh', NULL, 'Framework Transition', NULL, NULL, NULL, NULL),
  ('RU5', 'Immersive Tech Convergence Center', 'ITCC Main Folder', 'In progress', '2023', NULL, 'TIL_UEH', 'ISCM', 'Mr. Tâm', 'TuAnh-Lead, Prof Lee, Tài', NULL, 'Không', NULL, NULL, 'Tech Solutions', NULL),
  ('RU5.1', 'Immersive Tech Convergence Center', 'UEH-Nexus Urban Simulation Platform', 'Not start', '2026', NULL, 'New initiative', 'Tâm', 'Mr. Tâm', 'An, Chi, Hoài, Tài, Khôi, Hùng', 'Link', 'Không', 'Global Design', 'Human Centric Orientation', 'Tech Solutions', 'Urban System'),
  ('RU5.2', 'Immersive Tech Convergence Center', '4DGS - Realtime 3D reconstruction and motion hologram', 'In progress', '2026', '2027', 'New initiative', 'Tâm', 'Mr. Tâm', 'Tài', 'Link', 'Không', NULL, NULL, 'Tech Solutions', NULL),
  ('RU5.4', 'Immersive Tech Convergence Center', 'UEH-N Living Lab: E-History', 'In progress', '2023', '2027', 'Project', 'UEH', 'Mr. Hải', 'TuAnh-Lead, 3I, SMD', 'Meeting with members within the 1st week of June', 'Không', NULL, 'Human Centric Orientation', 'Tech Solutions', NULL),
  ('RU 10', 'Individual', 'Individual Research Main Folder', 'In progress', '2021', NULL, 'General Information', 'ISCM', 'Mr. Hoài', 'TuAnh-Lead', NULL, 'Không', NULL, NULL, NULL, 'Urban System'),
  ('RU10.1', 'Individual', 'Passive design', 'In progress', '2026', '2027', 'Project', 'Khang', 'Mr. Khang', NULL, NULL, 'Không', 'Global Design', 'Human Centric Orientation', NULL, NULL),
  ('RU1', 'MOVE System', 'MOVE System Main Folder', 'In progress', '2021', NULL, 'IRL_UEH', 'ISCM', 'Mr. Hoài', 'TuAnh-Lead, Prof Geert, An, Hoài, Hạnh An DCP, Mẫn VGU, Cường 3I, Tuấn NCS, Quang, Chi, Đường', 'Hoài upload thông tin làm UEH IRG: dl 15/6', 'Không', NULL, NULL, NULL, 'Urban System'),
  ('RU1.CE.1', 'MOVE System', 'CE-Rail@UEH_TOD', 'Done', '2025', '2026', 'Paper', 'ISCM', 'Mr. Bình', 'TuAnh-Lead', NULL, 'Không', NULL, NULL, NULL, 'Urban System'),
  ('RU1.SML.1', 'MOVE System', 'Smart Mobility Lab_UEH DRT Bus', 'In progress', '2026', '2026', 'Project', 'KICT/ISCM', 'Mr. Quang', 'TuAnh-Lead, Sandhya, Chi, DSA: Thao, Duy', 'Funded by K-City Network & kick-off meeting', 'Không', NULL, NULL, NULL, 'Urban System'),
  ('RU1.SML.2', 'MOVE System', 'Smart Mobility Lab_UEH e-motorbike', 'In progress', '2026', '2026', 'Research', 'UEH', 'Mr. Quang', 'TuAnh-Lead, Sandhya, An, Tân, Đường', 'Proceed w Datbike, Honda, a Paul', 'Không', NULL, NULL, NULL, 'Urban System'),
  ('RU1.SML.3', 'MOVE System', 'Smart Mobility Lab_ĐTCNN_Transportation research', 'In progress', '2025', '2026', 'Research', 'UEH', 'Mr. Quang', 'TuAnh-Lead, Lan, Đạo, Hiền, Vũ, An, Huyền SMD, Mai, Hoài', 'Coordinate all related projects', 'Không', NULL, NULL, NULL, 'Urban System'),
  ('RU2', 'Net Zero Open lab', 'NZ Main Folder', 'In progress', '2025', NULL, 'PL_UEH', 'ISCM', 'Ms. Sandhya', 'TuAnh-Lead, Trung Nexus, Đức, Quyên, Vũ Bạch, Cường 3I, Quang', NULL, 'Global Design', 'Global Design', 'Human Centric Orientation', 'Tech Solutions', NULL),
  (NULL, 'Net Zero Open lab', 'NZ center proposal', 'In progress', '2025', '2028', 'Research', 'ISCM', 'Ms. Sandhya', 'TuAnh-Lead, Trung Nexus, Đức, Quyên, Vũ Bạch, Cường 3I, Quang', NULL, 'Framework Transition', NULL, NULL, NULL, NULL),
  ('RU7', 'New Economy', 'New Economics Main Folder', 'In progress', '2021', '2026', 'IRL', 'ISCM', 'Mr. Hoài', 'TuAnh-Lead, Hạnh An DCP, Đức, Toàn', NULL, 'Không', NULL, NULL, NULL, 'Urban System'),
  ('RU4.2', 'New Economy', 'CL phát triển Đặc khu Côn Đảo', 'In progress', '2025', '2026', 'Project', 'HIDS/UBNDTPHCM', 'Mr. Hoài', 'TuAnh-Lead, Quang, Vũ', 'Revised report', 'Framework Transition', NULL, NULL, NULL, NULL),
  (NULL, 'New Economy', 'NE Platform', 'In progress', '2026', '2026', 'Project', 'Hải', 'Mr. Hải', NULL, NULL, 'Không', NULL, NULL, NULL, NULL),
  ('RU3', 'Public Space Lab', 'PSL Main Folder', 'In progress', '2026', NULL, 'PL', 'ISCM', 'Ms. Daniela', 'TuAnh-Lead, Minh, Hùng, Thư, Đạt', 'Link', 'Không', 'Global Design', 'Human Centric Orientation', NULL, NULL),
  ('RU3.1', 'Public Space Lab', 'HCR-PDPhung', 'Review', 'Apr2026', NULL, 'New initiative', 'UEH/Xuân Hòa Ward', 'Ms. Daniela', 'TuAnh-Lead, Minh, Hùng, Thư, Đạt', NULL, 'Không', 'Global Design', 'Human Centric Orientation', NULL, NULL),
  ('RU3.2', 'Public Space Lab', 'PS Atlas', 'In progress', '2026', '2027', 'Research', 'ISCM', 'Ms. Daniela', 'TuAnh-Lead, Minh, Hùng, Thư, Đạt', NULL, 'Không', 'Global Design', 'Human Centric Orientation', NULL, NULL),
  ('RU6', 'Smart City', 'SC Main Folder', 'In progress', '2022', NULL, 'IRL', 'ISCM', 'Mr. Tâm', 'TuAnh-Lead, Hoài, Chi, Hoài (Korea), An', NULL, 'Framework Transition', NULL, NULL, NULL, NULL),
  ('RU6.1', 'Smart City', 'RTD 2026 - Keynote Speakers', 'In progress', '2026', '2026', 'Event', 'UEH', 'Mr. Hoài', 'TuAnh-Lead', NULL, 'Không', NULL, NULL, NULL, 'Urban System'),
  ('RU6.2', 'Smart City', 'RTD 2026 - Special Sessions', 'In progress', '2026', '2026', 'Event', 'UEH', 'Mr. Tâm', 'TuAnh-Lead, Chi', NULL, 'Không', NULL, NULL, NULL, 'Urban System'),
  ('RU6.3', 'Smart City', 'RTD 2026 - Exhibition', 'In progress', '2026', '2026', 'Event', 'UEH', 'Mr. An', 'TuAnh-Lead, Tâm, Tài, Hùng', NULL, 'Không', NULL, NULL, NULL, 'Urban System'),
  ('RU6.13', 'Smart City', 'Đề án Smart City Cần Thơ', 'In progress', '2026', '2026', 'Project', 'ISCM/UEH', 'Mr. Tâm', 'TuAnh-Lead, Tâm, Chi, Hoài, Hoài (Korea), An', NULL, 'Framework Transition', NULL, NULL, 'Tech Solutions', 'Urban System'),
  ('RU6.15', 'Smart City', 'Cuộc thi thiết kế quốc tế IDC 2027', 'In progress', '2026', '2027', 'New initiative', 'UEH', 'Mr. Tâm', 'Tài, Tiên', NULL, 'Framework Transition', NULL, NULL, NULL, 'Urban System');
